/* ==================================================================== *
 * What one emulated firmware is asked, and what is recorded about it.
 *
 * Shared by the test and by `scripts/update-emulator-expectations.mjs`, so the
 * expectations are generated by exactly the code that later checks them. A
 * hand-written expectation rots; one produced by the measurement cannot claim
 * something the measurement never made.
 *
 * Every probe routes through the toolkit's own `SeekDevice` and
 * `WebUsbTransport`. Nothing here reimplements a protocol operation.
 * ==================================================================== */

import { readFileSync } from 'node:fs';

import { SeekError } from '../../src/errors.js';
import { SeekDevice } from '../../src/protocol/client.js';
import { OP } from '../../src/protocol/ops.js';
import { WebUsbTransport } from '../../src/protocol/webusb.js';
import { authPayload } from '../../src/profiles/legacy-auth.js';
import { buildModernWindowMap, FLASH_BASE } from '../../src/profiles/modern-4x.js';
import type { WindowEntry } from '../../src/profiles/types.js';
import type { Emulator } from './harness.js';

const HEX = (n: number, w = 2): string => `0x${n.toString(16).toUpperCase().padStart(w, '0')}`;

/* ---- what is asked -------------------------------------------------- */

/**
 * GetChipID. Wire id 54 (0x36) is not in the toolkit's `OP` table — the toolkit
 * has never needed it — so it is sent through the generic `rpcIn`, which is the
 * public raw-RPC door and needs no source change to use.
 *
 * The emulator scores its own `rpc` tier on this same wire id and records the
 * reply bytes rather than judging them, because the RPC table is per-firmware:
 * on the Compact PRO FF row 54 is GetChipID, and on a 2014 Compact it is
 * whatever that build put there. So this records bytes, not a chip id.
 */
export const WIRE_GET_CHIP_ID = 54;

/**
 * The commands whose presence is probed on every firmware.
 *
 * ONLY reads. `SetFeaturedFirmwareData` and `CompleteMemoryUpgrade` are the two
 * opcodes that erase and program, and they are deliberately absent: the
 * emulator's flash is copy-on-write and would survive them, but a probe suite
 * that sends a write opcode "because it is safe here" is one edit away from
 * being pointed at a camera.
 */
export const PROBED_COMMANDS: readonly { readonly name: string; readonly op: number }[] = [
  { name: 'GetErrorCode', op: OP.GET_ERROR_CODE },
  { name: 'GetOperationMode', op: OP.GET_OPERATION_MODE },
  { name: 'GetFeaturedFirmwareData(unarmed)', op: OP.GET_FEATURED_FIRMWARE_DATA },
  { name: 'GetFirmwareInfo', op: OP.GET_FIRMWARE_INFO },
  { name: 'GetChipID', op: WIRE_GET_CHIP_ID },
];

/** Bytes read from an armed window to locate it in the ground-truth image. */
export const LOCATOR_BYTES = 256;

/**
 * Control-IN request sizes probed against an armed window.
 *
 * `DEFAULT_READ_CHUNK` is 64 and `ops.ts` explains why: 64 is EP0's max packet
 * size, and some firmware serves most of a window at 256 and then never answers
 * the request that would empty it. That is a claim about real cameras, and this
 * measures the same thing per firmware: how many bytes actually come back for a
 * request of each size. A firmware that tops out below the requested size is
 * short-reading, which is exactly the behaviour `readArmed` adapts to.
 */
export const CONTROL_IN_SIZES: readonly number[] = [32, 64, 128, 256, 512];

/**
 * What the DEVICE did, not what the host called it.
 *
 * `timeout` and `transport error` were separate values once, and they were not
 * stable: on a firmware that had wedged its control endpoint, whether the host
 * reported "did not answer within 5 s" or "the session has ended" depended on
 * which side noticed first, so the same firmware pinned differently on
 * consecutive runs. Both mean one thing about the camera — IT DID NOT ANSWER —
 * so they are one value. A stall is different: that is the device refusing, and
 * it is a real reply.
 */
export type CommandOutcome = 'ok' | 'stall' | 'device-error' | 'no-answer';

export interface IdentityProbe {
  readonly vendorId: string;
  readonly productId: string;
  readonly manufacturerName: string | null;
  readonly productName: string | null;
  readonly serialNumber: string | null;
}

export interface WindowProbe {
  readonly subcmd: number;
  /** The address `modern-4x`'s selector map claims for this subcommand. */
  readonly claimedAddress: string | null;
  /** True when BeginFirmwareUpgrade armed it and GetErrorCode came back 0. */
  readonly armed: boolean;
  /** The device error code after arming, or null when the arm threw. */
  readonly errorCode: number | null;
  /**
   * TRUE when the bytes served equal the image at the address the profile CLAIMS.
   *
   * This is the verdict, and it is a DIRECT comparison rather than a search. An
   * earlier version searched the image for the served bytes and asked whether
   * the claimed address was among the hits — which was WRONG, because the hit
   * list has to be capped: a window whose first 256 bytes are a constant run
   * occurs in hundreds of places, the cap truncated the list before it reached
   * the claimed address, and eleven perfectly correct windows were recorded as
   * "misplaced". Tier 2 dumping those same firmwares with zero differing bytes
   * is what exposed it. Comparing at the claimed address cannot make that
   * mistake, and it is cheaper.
   */
  readonly matchesClaimed: boolean;
  /**
   * Where else those bytes occur in the 4 MiB image — DIAGNOSIS ONLY, capped.
   *
   * Decidable only because the erased regions were filled with a seeded stream;
   * over erased flash the locator would be 0xFF and would match everywhere.
   * Several hits is a real result, not a failure: a factory part ships slot A,
   * slot B and recovery holding the same bank. `mappedTruncated` says the list
   * hit the cap, which means "these bytes carry little positional information",
   * never "they came from the wrong place".
   */
  readonly mappedAddresses: readonly string[];
  readonly mappedTruncated: boolean;
  /** The single hit, when there is exactly one. */
  readonly mappedAddress: string | null;
  readonly locatorHex: string | null;
  readonly error: string | null;
}

export interface AuthProbe {
  /** A plain 2-byte BeginFirmwareUpgrade armed the protected bank. */
  readonly plainAccepted: boolean;
  /** The 18-byte authenticated payload armed the protected bank. */
  readonly authAccepted: boolean;
  /** A payload with the right length and a WRONG token. */
  readonly wrongTokenAccepted: boolean;
  readonly subcmd: number;
}

export interface Tier1Result {
  readonly entryId: string;
  readonly identity: IdentityProbe;
  readonly chipIdHex: string | null;
  readonly commands: Readonly<Record<string, CommandOutcome>>;
  readonly windows: readonly WindowProbe[];
  readonly auth: AuthProbe;
  /** Bytes actually returned for a control IN of each probed size. */
  readonly controlInBytes: Readonly<Record<string, number | null>>;
  /** sha256 of the 4 MiB image the emulator says it is serving. */
  readonly servedSha256: string;
  readonly fillSeed: number | null;
  readonly fillScope: string | null;
  readonly bytesStillErased: number | null;
}

/* ---- the probe ------------------------------------------------------ */

export interface ProbeOptions {
  /** Path to the emulator's `--flash-out` image. Needed for the map probe. */
  readonly groundTruthPath: string;
  readonly urbTimeoutMs?: number;
  /** Subcommands to probe. Default: the whole `modern-4x` selector map. */
  readonly windowMap?: readonly WindowEntry[];
}

async function outcome(run: () => Promise<unknown>): Promise<CommandOutcome> {
  try {
    await run();
    return 'ok';
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (/stall/i.test(message)) return 'stall';
    if (/returned 0x/i.test(message)) return 'device-error';
    return 'no-answer';
  }
}

/** Every offset at which `needle` occurs in `hay`, capped so a constant-run
 *  locator cannot produce a million-entry list. DIAGNOSIS ONLY — the verdict
 *  comes from `sameAt()`, which cannot be fooled by the cap. */
function locateAll(
  hay: Uint8Array,
  needle: Uint8Array,
  cap = 16,
): { at: number[]; truncated: boolean } {
  const h = Buffer.from(hay.buffer, hay.byteOffset, hay.byteLength);
  const n = Buffer.from(needle.buffer, needle.byteOffset, needle.byteLength);
  const out: number[] = [];
  let at = h.indexOf(n);
  while (at >= 0) {
    if (out.length === cap) return { at: out, truncated: true };
    out.push(at);
    at = h.indexOf(n, at + 1);
  }
  return { at: out, truncated: false };
}

/** Do `got`'s bytes equal `hay` starting at `offset`? */
function sameAt(hay: Uint8Array, offset: number, got: Uint8Array): boolean {
  if (offset < 0 || offset + got.length > hay.length) return false;
  for (let i = 0; i < got.length; i++) if (hay[offset + i] !== got[i]) return false;
  return true;
}

export async function probeTier1(emu: Emulator, options: ProbeOptions): Promise<Tier1Result> {
  const device = await emu.attach(
    options.urbTimeoutMs === undefined ? {} : { urbTimeoutMs: options.urbTimeoutMs },
  );
  const transport = new WebUsbTransport(device, {
    recipient: 'auto',
    api: 'usbip (emulator)',
    host: 'vitest',
  });
  const seek = new SeekDevice(transport);

  /**
   * Close and reopen, tolerating failure.
   *
   * `dump.ts` says the only thing that clears a camera which has wedged its
   * control endpoint is a close/reopen, and the probe deliberately sends things
   * that get refused. Recovering between independent measurements is what stops
   * one refusal from being recorded as sixty-three.
   */
  const recover = async (): Promise<void> => {
    try {
      await transport.close();
      await transport.open();
    } catch {
      /* The device is gone; whatever is measured next will say so. */
    }
  };

  try {
    await transport.open();

    const identity: IdentityProbe = {
      vendorId: HEX(transport.description.vendorId, 4),
      productId: HEX(transport.description.productId, 4),
      manufacturerName: transport.description.manufacturerName,
      productName: transport.description.productName,
      serialNumber: transport.description.serialNumber,
    };

    /* ---- GetChipID ---- */
    let chipIdHex: string | null = null;
    try {
      const raw = await seek.rpcIn(WIRE_GET_CHIP_ID, 12);
      chipIdHex = Buffer.from(raw).toString('hex');
    } catch {
      chipIdHex = null;
    }

    /* ORDER MATTERS AND IS NOT ARBITRARY.
     * The selector map is the measurement this whole tier exists for, so it runs
     * FIRST, before anything that could wedge the control endpoint. The command
     * probe deliberately sends things the firmware may refuse — an unarmed
     * GetFeaturedFirmwareData stalls by design — so it runs LAST, where a wedge
     * costs one recorded outcome instead of the whole row. */
    /* ---- the selector map, DERIVED from what came back ---- */
    const truth = new Uint8Array(readFileSync(options.groundTruthPath));
    const claimed = new Map<number, number>();
    for (const entry of options.windowMap ?? buildModernWindowMap()) {
      claimed.set(entry.subcmd, entry.address);
    }

    const windows: WindowProbe[] = [];
    for (const [subcmd, address] of [...claimed].sort((a, b) => a[0] - b[0])) {
      let armed = false;
      let errorCode: number | null = null;
      let matchesClaimed = false;
      let mappedAddresses: string[] = [];
      let mappedTruncated = false;
      let locatorHex: string | null = null;
      let error: string | null = null;
      try {
        await seek.armWindow({ subcmd, address, note: 'probe' });
        armed = true;
        errorCode = 0;
        const read = await seek.readArmed(64, LOCATOR_BYTES);
        if (read.data.length === LOCATOR_BYTES) {
          locatorHex = Buffer.from(read.data.subarray(0, 16)).toString('hex');
          matchesClaimed = sameAt(truth, address - FLASH_BASE, read.data);
          const found = locateAll(truth, read.data);
          mappedAddresses = found.at.map((at) => HEX(FLASH_BASE + at, 8));
          mappedTruncated = found.truncated;
        } else {
          error = read.stopReason ?? `short locator read (${String(read.data.length)} B)`;
        }
      } catch (e) {
        error = e instanceof Error ? e.message : String(e);
        const code = /returned (0x[0-9a-f]+)/i.exec(error);
        if (code?.[1]) errorCode = Number.parseInt(code[1], 16);
        /* Every subcommand is measured INDEPENDENTLY. A refusal can leave the
         * control endpoint wedged, and `dump.ts` says the only thing that clears
         * that is a close/reopen — so do exactly that, or one unreadable window
         * would be recorded as sixty-three.
         *
         * EXCEPT for a mode failure. `device/mode` means `ensureMode0()` read the
         * mode, wrote it, and read it back for three seconds without it changing:
         * the endpoint demonstrably answered throughout, so there is nothing to
         * clear, and reopening would add a re-import per subcommand to a firmware
         * that already costs three seconds per arm. */
        if (!(e instanceof SeekError && e.code === 'device/mode')) await recover();
      }
      windows.push({
        subcmd,
        claimedAddress: HEX(address, 8),
        armed,
        errorCode,
        matchesClaimed,
        mappedAddresses,
        mappedTruncated,
        mappedAddress: mappedAddresses.length === 1 ? (mappedAddresses[0] ?? null) : null,
        locatorHex,
        error,
      });
    }

    /* ---- how many bytes a control IN of each size really returns ---- */
    const controlInBytes: Record<string, number | null> = {};
    for (const size of CONTROL_IN_SIZES) {
      await recover();
      try {
        await seek.armWindow({ subcmd: 5, address: 0, note: 'ep0 probe' });
        const raw = await seek.rpcIn(OP.GET_FEATURED_FIRMWARE_DATA, size);
        controlInBytes[String(size)] = raw.length;
      } catch {
        controlInBytes[String(size)] = null;
      }
    }

    /* ---- the auth channel, as an OBSERVATION ----
     * `DeviceEvidence.authSelectorWorks` in the toolkit says in as many words
     * that the observation which would settle whether the authenticated channel
     * is REQUIRED — a plain arm of a protected bank coming back refused — "is
     * not made anywhere yet". The emulator runs the firmware's real dispatch, so
     * it can be made here. Slot A (subcmd 5) is the protected bank the legacy
     * firmware locks; a wrong-token payload is sent too, because "the 18-byte
     * form armed it" and "the token was checked" are different claims. */
    const AUTH_SUBCMD = 5;
    const wrong = authPayload(AUTH_SUBCMD);
    wrong[2] = (wrong[2] ?? 0) ^ 0xff;
    /* EACH OF THE THREE IS MEASURED FROM A FRESH TRANSPORT.
     *
     * On the firmware this question is actually about, the plain arm is REFUSED
     * — that is the whole point — and a refusal can leave the control endpoint
     * wedged. Running the authenticated arm straight afterwards was measuring
     * the wedge, not the token: the same firmware reported `authAccepted` true
     * on one run and false on the next. Recovering between them makes each
     * answer a property of the firmware. */
    const armAuth = async (payload?: Uint8Array): Promise<boolean> => {
      await recover();
      const entry: WindowEntry =
        payload === undefined
          ? { subcmd: AUTH_SUBCMD, address: 0, note: 'auth probe' }
          : { subcmd: AUTH_SUBCMD, address: 0, note: 'auth probe', payload };
      return (await outcome(() => seek.armWindow(entry))) === 'ok';
    };
    const auth: AuthProbe = {
      subcmd: AUTH_SUBCMD,
      plainAccepted: await armAuth(),
      authAccepted: await armAuth(authPayload(AUTH_SUBCMD)),
      wrongTokenAccepted: await armAuth(wrong),
    };

    /* ---- which commands answer ---- */
    const commands: Record<string, CommandOutcome> = {};
    for (const { name, op } of PROBED_COMMANDS) {
      await recover();
      commands[name] = await outcome(() => seek.rpcIn(op, 4));
    }
    await recover();
    commands.BeginFirmwareUpgrade = await outcome(() =>
      seek.rpcOut(OP.BEGIN_FIRMWARE_UPGRADE, new Uint8Array([0x05, 0x00])),
    );
    await recover();
    commands.SetFirmwareInfoFeatures = await outcome(() =>
      seek.rpcOut(OP.SET_FIRMWARE_INFO_FEATURES, new Uint8Array([0x01, 0x00])),
    );
    await recover();
    /* ensureMode0(), NOT a bare SetOperationMode(0).
     *
     * A bare one was what this probe did first, and on the Compact / Compact XR /
     * Nano 200 builds it NEVER ANSWERS: the control OUT times out, the endpoint
     * stays wedged, and every later transfer fails — which read as "this firmware
     * refuses all 63 windows" until tier 2 dumped the same firmware perfectly.
     * `ensureMode0()` reads the mode first and returns without writing when it is
     * already 0, which those builds are. The toolkit was right and the probe was
     * wrong; what is recorded here is the toolkit's own guarded path. */
    commands.EnsureMode0 = await outcome(() => seek.ensureMode0());

    return {
      entryId: emu.entryId,
      identity,
      chipIdHex,
      commands,
      windows,
      auth,
      controlInBytes,
      servedSha256: emu.ready.flash_sha256,
      fillSeed: emu.ready.fill?.seed ?? null,
      fillScope: emu.ready.fill?.scope ?? null,
      bytesStillErased: emu.ready.fill?.bytes_still_erased ?? null,
    };
  } finally {
    await transport.close().catch(() => undefined);
    await device.close().catch(() => undefined);
  }
}
