/**
 * `@seek-fw/core` — the whole toolkit as one dependency-free, isomorphic
 * library.
 *
 * Nothing here touches the DOM, `process`, `node:fs` or a `Blob`. The only host
 * capability core depends on is WebCrypto's SHA-256, which is a global in both
 * browsers and Node. Workflows RETURN `Artifact[]`; the web app downloads them
 * and the CLI writes them to disk.
 *
 * The exports are grouped by layer, from the bottom up. Two names are aliased
 * because they collide across layers — `TransportInfo` (the live transport vs.
 * its manifest record) and `EmbeddedKeyTable` (the located key pair vs. its
 * manifest record) — and the aliases always go to the manifest side, since the
 * structural type is the one callers reach for more often.
 */

/* ---- bytes, hex and hashing ------------------------------------------ */
export {
  addrTag,
  asciiz,
  bytesToHex,
  concatBytes,
  equalBytes,
  findAll,
  hex,
  hexDump,
  hexToBytes,
  hexUp,
  isoStamp,
  parseNumber,
  sha256hex,
  utf8,
  viewOf,
} from './bytes.js';

/* ---- error taxonomy --------------------------------------------------- */
export { CancelledError, SeekError, errorMessage, isSeekError } from './errors.js';
export type { SeekErrorCode, SeekErrorOptions } from './errors.js';

/* ---- progress, logging and outputs ------------------------------------ */
export { collectingReporter, prefixed, silentReporter, withLevelMap } from './events.js';
export type {
  Artifact,
  ArtifactEvent,
  LogEvent,
  LogLevel,
  ProgressEvent,
  ProgressUnit,
  Reporter,
  RunEvent,
} from './events.js';

/* ---- the cipher and cryptanalytic key recovery ------------------------ */
export {
  CANDIDATE_K,
  CHECK_ZERO_IDX,
  KEY_SUFFIX_RE,
  KNOWN_ZERO_IDX,
  BOOT_CONFIG_BASE,
  Xorshift128,
  checksum32,
  cloneState,
  cryptBytes,
  cryptImage,
  decryptImage,
  describeKeyTableMismatch,
  findEmbeddedKeyTable,
  findKeyCandidates,
  identifyKey,
  isEncryptedWord,
  keyFilenameSuffix,
  keyFromState,
  keyTableWhere,
  parseKeyFilenameSuffix,
  pickKeyTable,
  recoverKeyInfo,
  recoverState,
  resolveWhitening,
  sameState,
  stateFromKey,
  stateOf,
  storeKeyOf,
  xsNext,
} from './crypto/index.js';
export type {
  EmbeddedKeyTable,
  KeyConfidence,
  KeyIdentity,
  KeyPair,
  KeyTableCandidate,
  KeyUnderK,
  PickedKeyTable,
  RecoveredKey,
  SlotKeyEvidence,
  StoreKey,
  WhiteningResolution,
  Xorshift128State,
} from './crypto/index.js';

/* ---- image headers, footers and bank payloads ------------------------- */
export {
  ADJUST_OFFSET,
  DEFAULT_WINDOW_SIZE,
  FOOTER_MODEL_LENGTH,
  FOOTER_MODEL_OFFSET,
  FOOTER_SIZE,
  FOOTER_TAG,
  HEADER_OFFSET,
  HEADER_SIZE,
  IMAGE_MAGIC,
  LENGTH_OFFSET,
  MAX_IMAGE_LEN,
  SLOT_STEP,
  TRY_KEYS_MAX_LEN,
  assertBankPayload,
  bankPayloadSize,
  buildBankPayload,
  findImages,
  footerOffsetFor,
  parseFooter,
  parseImageHeader,
  setAcceptSum,
  transferSum16,
  versionString,
  wordSum32,
} from './image/index.js';
export type {
  AcceptSumResult,
  BankPayload,
  ImageFooter,
  ImageHeader,
  ImageSlot,
} from './image/index.js';

/* ---- USB protocol: opcodes, the transport boundary, the client -------- */
export {
  COMMIT_WORST_CASE_MS,
  CONFIGURATION_VALUE,
  DEFAULT_READ_CHUNK,
  MAX_CONTROL_IN,
  EP0_BUF,
  ERR_BAD_CHECKSUM,
  FLASH_OPS,
  INTERFACE_NUMBER,
  MIN_READ_CHUNK,
  MODE_SETTLE_MS,
  OP,
  OP_DIRECTION,
  READ_ONLY_OPS,
  SAFE_BEFORE_IDENTITY,
  SEEK_VENDOR_ID,
  SeekDevice,
  USB_COMMIT_TIMEOUT_MS,
  USB_PROBE_TIMEOUT_MS,
  USB_TIMEOUT_MS,
  WALL_CLOCK,
  WINDOW_SIZE,
  WebUsbTransport,
  assertOpSetsDisjoint,
  isFlashOp,
  isPlatformClaimRefusal,
  isReadOnlyOp,
  u16Payload,
  withTimeout,
} from './protocol/index.js';
export type {
  ChunkListener,
  DeadlineClock,
  DeviceDescription,
  OpName,
  Opcode,
  ReadResult,
  Recipient,
  RecipientPreference,
  SeekDeviceOptions,
  TransportInfo,
  UsbBackend,
  UsbTransport,
  WebUsbConfiguration,
  WebUsbControlSetup,
  WebUsbDevice,
  WebUsbInTransferResult,
  WebUsbOutTransferResult,
  WebUsbTransferStatus,
  WebUsbTransportOptions,
} from './protocol/index.js';

/* ---- firmware profiles: the registry and its built-in families -------- */
export {
  AMBIGUITY_MARGIN,
  CONFIDENT_SCORE,
  GENERIC_BASELINE,
  ACCEPT_SUM,
  DEVICE_KEY_SLOT_LENGTH,
  DEVICE_KEY_SLOT_OFFSET,
  FLASH_BASE,
  FLASH_K,
  FLASH_SIZE,
  GAP_ADDRESS,
  LEGACY_KNOWN_VERSIONS,
  MODERN_BOOT,
  MODERN_CIPHER,
  MODERN_MEMORY,
  MODERN_SLOTS,
  MODERN_SWEEP_RANGE,
  OLD_FW_UNLOCK_TOKEN,
  SLOT_A_BASE,
  SLOT_B_BASE,
  SLOT_RECOVERY_BASE,
  SUPPORTED,
  TIE_MARGIN,
  buildLegacyWindowMap,
  buildModernWindowMap,
  buildWindowPlan,
  compact2014,
  compact2016,
  detectProfile,
  generic,
  getProfile,
  hasCapability,
  legacyAuth,
  legacyReaderOp,
  legacySelectorRows,
  legacyWindowPlan,
  listProfiles,
  modern4x,
  modernWindowPlan,
  parseVersion,
  primaryVersion,
  registerProfile,
  requireCapability,
  unsupported,
  versionSource,
  versionsIn,
} from './profiles/index.js';
export type {
  BootPolicy,
  BootPrediction,
  CapabilityName,
  FirmwareVersion,
  CipherProfile,
  DetectionResult,
  DetectionVerdict,
  DeviceEvidence,
  FirmwareProfile,
  MemoryLayout,
  ProfileCapabilities,
  ProfileId,
  ProfileMatch,
  SelectorRow,
  SlotDescriptor,
  SlotKey,
  Support,
  UnreachableRange,
  WindowEntry,
  WindowPlan,
} from './profiles/index.js';

/* ---- output packaging: manifests, READMEs and the ZIP writer ---------- */
export {
  buildBootloaderKeysSummary,
  buildDecryptionFailed,
  buildDecryptionNotAttempted,
  buildDecryptionSummary,
  buildDumpManifest,
  buildGapRecord,
  buildImageSummary,
  buildKeySummary,
  buildLegacyDumpManifest,
  buildOfflineDecryptManifest,
  buildSelectorRecord,
  buildSweepManifest,
  buildWindowRecord,
  buildZip,
  crc32,
  makeLegacyReadme,
  makeOfflineDecryptReadme,
  makeReadme,
  makeSweepReadme,
  manifestToJson,
  zipEntryCount,
  zipTotalDataSize,
} from './archive/index.js';
export type {
  BootloaderKeysSummary,
  DecryptionAttempted,
  DecryptionNotAttempted,
  DecryptionSummary,
  DeviceInfo,
  DumpManifest,
  EmbeddedKeyTable as EmbeddedKeyTableRecord,
  GapRecord,
  ImageSummary,
  KeySummary,
  LegacyDumpManifest,
  ManifestProfileInfo,
  OfflineDecryptManifest,
  OfflineDecryptSource,
  SelectorRecord,
  SelectorTableInfo,
  ShortfallFill,
  SweepManifest,
  TransportInfo as TransportInfoRecord,
  WindowRecord,
  WindowRecordError,
  WindowRecordRead,
} from './archive/index.js';

/* ---- the five workflows ----------------------------------------------- */
export {
  DEFAULT_DUMP_OPTIONS,
  assertFlashable,
  bootedSlot,
  decryptDump,
  describeDevice,
  detectProfileForDump,
  deviceInfoOf,
  entryForAddress,
  evidenceFromChannelProbe,
  evidenceFromDump,
  flashInvalidatesAnalysis,
  identifyCamera,
  identityGate,
  identityRefusal,
  isCancelled,
  planForDevice,
  predatesDumpProtocol,
  predatesDumpProtocolReason,
  prepareImage,
  probeSelectorChannel,
  profileInfoOf,
  readDeviceInfo,
  readRunningFirmware,
  resolveDumpOptions,
  runDump,
  runSweep,
  slotByKey,
  targetSlot,
  transportInfoOf,
  unlockTokenOf,
  usesAuthChannel,
  versionUnknownReason,
  writeFirmware,
  VERSION_READ_ATTEMPTS,
  VERSION_READ_STARTUP_READS,
  VERSION_READ_STARTUP_SPACING_MS,
  VERSION_READ_STARTUP_WINDOW_MS,
} from './workflows/index.js';
export type {
  CameraIdentification,
  ComparisonRow,
  DecryptOptions,
  SelectorChannelProbe,
  DecryptResult,
  DecryptedSlot,
  DeviceState,
  DumpOptions,
  DumpResult,
  IdentityGate,
  KeyPatchRecord,
  PlannedOperation,
  PreparedFlash,
  SlotState,
  SweepResult,
  WorkflowContext,
} from './workflows/index.js';

/* ---- the v1 full-flash preservation pipeline ---------------------------- */
export {
  BACKUP_WINDOW_COUNT,
  BANKS,
  BLANK_CFG_BANK,
  BOOT_CONFIG_ADDRESS,
  BOOT_CONFIG_BYTES,
  CFG_MODE,
  DRAIN_RETRIES,
  PRESERVE_BACKUP_FILE,
  PRESERVE_BANK_CAPTURE_FILE,
  PRESERVE_DUMP_MANIFEST_FILE,
  PRESERVE_DUMP_ORIGINAL_FILE,
  PRESERVE_DUMP_POSTWRITE_FILE,
  PRESERVE_DUMP_README_FILE,
  PRESERVE_PATCHED_FILE,
  PRESERVE_PLAIN_NAME,
  PRESERVE_RUN_STATE_FILE,
  PRESERVE_STEP_IDS,
  PostResetWedgeError,
  PROBE_OFFSET,
  READ_CHUNK,
  RESET_OP,
  STAGE_CHUNK,
  V1_2014_PATCH_SITES,
  V1_PAYLOAD_VMA_BASE,
  WIDENED_MODE,
  REBALANCE_WORD_OFFSET,
  WINDOW_BYTES,
  assembleBackupImage,
  backupResultFromImage,
  backupSlice,
  backupWindows,
  bankWindow,
  buildV1Patch,
  cfgWindow,
  commitToBank,
  conjugateCapture,
  createPreserveRun,
  describeStepGate,
  detectActiveSlot,
  drainExact,
  drainWholePart,
  isPreserveStepId,
  keystream,
  nextStepAfter,
  parseBootConfig,
  postProcessDump,
  preservationWindows,
  probeWidenedWindow,
  readVersion,
  recordStepFailure,
  resetDevice,
  resetOpPayload,
  runPreserveStep,
  runPreservationPipeline,
  solvePlainFromCapture,
  sum16,
  verifyAgainstBackup,
  verifyCapture,
  widenedWindow,
  wordSum,
  xorWindowVerbatim,
} from './preservation/index.js';
export type {
  BackupResult,
  BankKey,
  CommitRouteId,
  CreatePreserveRunOptions,
  CreatedPreserveRun,
  DrainCapability,
  PatchSite,
  PipelineArtifacts,
  PipelineOptions,
  PipelineRecord,
  PreserveArtifactLoader,
  PreservePatchSummary,
  PreserveRunState,
  PreserveStepId,
  PreserveStepOutcome,
  PreserveStepRecord,
  RestoreFormId,
  SessionOpener,
  SlotDetection,
  SolvePlainResult,
  StagedFormId,
  V1Patch,
  WindowBytes,
} from './preservation/index.js';
